# CI for Ad Service
name: ad-service-ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Run Checkstyle
        working-directory: src/ad
        run: |
          chmod +x ./gradlew 
          ./gradlew checkstyleMain checkstyleTest

      - name: Run SpotBugs
        working-directory: src/ad
        run: |
          chmod +x ./gradlew
          ./gradlew spotbugsMain spotbugsTest

      - name: Run PMD
        working-directory: src/ad
        run: |
          chmod +x ./gradlew
          ./gradlew pmdMain pmdTest

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Build with Gradle
        run: |
          cd src/ad
          chmod +x ./gradlew
          ./gradlew installDist    # Build distribution (like packaging app)

      - name: Run Unit Tests
        run: |
          cd src/ad
          ./gradlew test

  image-update:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: src/ad
          file: src/ad/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/otel-demo-ad-service:${{ github.run_id}}

  update-k8s-manifest:
    runs-on: ubuntu-latest

    needs: [build, image-update]

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.44.1/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - name: Update tag in kubernetes deployment manifest
        run: |
          yq -i '
            (. | select(.kind == "Deployment" and .metadata.name == "opentelemetry-demo-adservice")
            .spec.template.spec.containers[].image) = "${{ secrets.DOCKER_USERNAME }}/otel-demo-ad-service:${{ github.run_id }}"
          ' kubernetes/ad/deploy.yaml

      - name: Update tags in kubernetes three-deploy manifest
        run: |
          yq -i '
          (. | select(.kind == "Deployment" and .metadata.name == "opentelemetry-demo-adservice")
          .spec.template.spec.containers[].image) = "${{ secrets.DOCKER_USERNAME }}/otel-demo-ad-service:${{ github.run_id }}" |

          (. | select(.kind == "Deployment" and .metadata.name == "opentelemetry-demo-productcatalogservice")
          .spec.template.spec.containers[].image) = "${{ secrets.DOCKER_USERNAME }}/otel-demo-product-catalog-service:${{ github.run_id }}" |

          (. | select(.kind == "Deployment" and .metadata.name == "opentelemetry-demo-recommendationservice")
          .spec.template.spec.containers[].image) = "${{ secrets.DOCKER_USERNAME }}/otel-demo-recommendation-service:${{ github.run_id }}"
          ' kubernetes/three-deploy.yaml

      - name: Commit and push changes
        run: |
          git config --global user.email "mohdsaud1523@gmail.com"
          git config --global user.name "Saud215"
          git add kubernetes/ad/deploy.yaml kubernetes/three-deploy.yaml
          git commit -m "[CI]: Update microservice image tags" || echo "No changes to commit"
          git push origin HEAD:main
