# CI for Ad Service
name: ad-service-ci

on:
  pull_request:
    branches:
      - main

jobs:
  lint-and-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Run Checkstyle
        working-directory: src/ad
        run: |
          chmod +x ./gradlew 
          ./gradlew checkstyleMain checkstyleTest

      - name: Run SpotBugs
        working-directory: src/ad
        run: |
          chmod +x ./gradlew
          ./gradlew spotbugsMain spotbugsTest

      - name: Run PMD
        working-directory: src/ad
        run: |
          chmod +x ./gradlew
          ./gradlew pmdMain pmdTest

  build:
    runs-on: ubuntu-latest

    needs: [lint-and-analysis]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Build with Gradle
        run: |
          cd src/ad
          chmod +x ./gradlew
          ./gradlew installDist    # Build distribution (like packaging app)

      - name: Run Unit Tests
        run: |
          cd src/ad
          ./gradlew test

  docker:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: src/ad
          file: src/ad/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/otel-demo-ad-service:latest

