name: recommendation-service-ci

on:
  pull_request:
    branches:
      - main

jobs:
  lint-and-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        working-directory: src/recommendation
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 bandit

      - name: Run Flake8 (style/linting)
        working-directory: src/recommendation
        run: flake8 .

      - name: Run Bandit (security scan)
        working-directory: src/recommendation
        run: bandit -r .

  build:
    runs-on: ubuntu-latest
    needs: [lint-and-analysis]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        working-directory: src/recommendation
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        working-directory: src/recommendation
        run: |
          echo "No tests available yet!"

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: src/recommendation
          file: src/recommendation/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/otel-demo-recommendation-service:latest

